### ISSUE TITLE
Строка

### ISSUE THREAD

**Issue by casa7x** [Tatsianazhylevich/To-Do-list#1]
https://github.com/Tatsianazhylevich/To-Do-list/blob/f321748fe0e9b673c8b1fedaf83033d7cfd77201/script.js#L27

Зачем ты оборачиваешь в строку? у тебя разве и так они не в виде строки приходят? Чуть выше, ты же проверку делаешь)

**Comment by Tatsianazhylevich** [comment]
Убрала "обертку"
